### ISSUE TITLE
empty cvs file

### ISSUE THREAD

**Issue by liudger** [tvwerkhoven/domoticz2influxdb#1]
When running the domoticz2influxdb.py on an exported database the resulted cvs file is empty. I this an issue with the format of the domoticz database? There are no errors.

**Comment by sylvaingiraud** [comment]
Similar but I don't even have the "influx_data.csv" file created running:
sudo python ./domoticz2influxdb.py domoticz/domoticz.db
No error as well.
What's wrong?

**Comment by tvwerkhoven** [comment]
Did you specify device IDs to export with `--devids`? If not, none are exported, as explained in the `--help` text. I've now changed this to export all (supported) devices instead.

**Comment by averter** [comment]
Same issue here even when using `--devids`
````
python domoticz2influxdb.py --devids=20 ../domoticz/domoticz.db
````
outputs
```` python
Traceback (most recent call last):
  File "domoticz2influxdb.py", line 170, in <module>
    main()
  File "domoticz2influxdb.py", line 163, in main
    get_data(args.domoticzdb, tid, meterquery=args.meterquery, multimeterquery=args.multimeterquery, tempquery=args.tempquery, outfile=args.influxfile)
  File "domoticz2influxdb.py", line 56, in get_data
    get_temperature(dbpath, dev_id, dev_name, tempquery, outfile)
  File "domoticz2influxdb.py", line 116, in get_temperature
    date_epoch = int(dt.datetime.strptime(date, "%Y-%m-%d").timestamp() + 12*3600) 
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'
````
which suggests an issue regarding timestamp?
